### ISSUE TITLE
Can only see cooldowns

### ISSUE THREAD

**Issue by fractured** [Foglio1024/Tera-custom-cooldowns#11]
Hello, 
I'm having this issue since 1.3, for some reason I can only see my cooldowns window. Trying to unhide others also does nothing.

**Comment by Foglio1024** [comment]
There is an issue with TCC windows going under TERA window. I'm still not sure what's causing it, since it seems to happen randomly.

**Comment by fractured** [comment]
I'm not sure if that's the bug though, restarting does nothing. When going windowed mode and resizing the game window, there's nothing behind the client as well, other than cooldowns bar.

**Comment by Foglio1024** [comment]
Try this: close TCC, open your settings.csv file and make sure that last value for each row is Visible and not Hidden or Collapsed.

**Comment by fractured** [comment]
All of the settings are already set to visible, switching them around and messing with positional numbers also did not help.

**Comment by Foglio1024** [comment]
Should be fixed in v0.1.5

**Comment by fractured** [comment]
For some reason this issue still persists in 1.6, only cooldowns and boss bar is visible atm.

**Comment by Foglio1024** [comment]
Try deleting the settings.csv file and restarting TCC and Tera. If it doesen't work in don't know what the issue could be, maybe something related to some operating systems.
