### ISSUE TITLE
HH ph1, ph2 boss bars

### ISSUE THREAD

**Issue by crvN** [Foglio1024/Tera-custom-cooldowns#24]
TCC doesn't show boss debuffs correctly on ph1, and doesn't switch to Vergos hp bar until ballistas phase start.

**Comment by Foglio1024** [comment]
That's what I wanted to test, but the random raid I joined didn't make it to ph2. As for the debuffs I noticed it not working correctly during today's last try, so I didn't have the time to check it better.

**Comment by Foglio1024** [comment]
Fixed ph2 boss bar in bad7084c962472a95165ced17d3366c278c54e5a.

**Comment by Foglio1024** [comment]
Ok, I found the cause of the other issue. Debuffs are paused when switching between bosses, so going back to previous dragon loads debuffs with the cooldown they had when the player switched to new boss.

**Comment by Foglio1024** [comment]
Fixed other issue in dfe9258a232b26a85e9141f97830abe674ddaf94. It still needs more testing though.

**Comment by crvN** [comment]
Looks like debuffs under boss bars still broken on ph1. And can you make them bigger a bit?

**Comment by Foglio1024** [comment]
Can you explain better what you mean with broken please? Also yes, I'm reworking most UI parts so I'll increase their size a bit.

**Comment by crvN** [comment]
It shows debuffs only of one boss, while should show of all bosses, right? And as I notice debuffs are always under bottom left hp bar. Maybe I'm wrong, because today was awful raid, so I res and heal my party mostly.

**Comment by Foglio1024** [comment]
No, it's supposed to show the debuffs of the current boss only.

**Comment by crvN** [comment]
Then I don't see any issues anymore, probably can be closed. :)
